### PR TITLE
Build process update for Linux

### PR DESCRIPTION
**Pull request by instance-id**
### Description
Update to build process for Linux systems

### Related issues
https://github.com/GimelStudio/GimelStudio/issues/118

### Systems Tested On
Pop_OS 21.04

### Checklist
- [x] I signed the [CLA](https://cla-assistant.io/GimelStudio/GimelStudio)
- [x] There are no unnecessary or out-of-scope changes in this PR
- [x] Gimel Studio runs successfully on the above system(s) with the changes in this PR
- [x] The changes in this PR follow the [style guides](https://github.com/GimelStudio/GimelStudio/blob/master/CONTRIBUTING.md#styleguides)

### CODE REVIEW

**Comment by Correct-Syntax** [comment]
Thanks for the PR. Great work. I am going to merge this. 👍 

Just curious: is there is a specific reason why there is a mix of snake-case and camel-case for variables? Not that is matters too much since it is a minor thing that can be fixed later if needed. 😄

**Comment by instance-id** [comment]
There is a reason, but it's not a very good one, lol. I do a lot of C# development and have been used to doing camel-case, but forced myself to use snake-case with python as I was always told it was "the standard" (I personally prefer camel), so I had gotten used to doing so, but then I noticed that you guys were using camel-case, which kind of threw me for a loop and I kept having to go back and redo them, so I eventually said "worry about it later" and I just used snake-case while building things at then just before I submitted I went through and tried to change them over to camel, but as I look again, I see that I missed some. So my apologies about that.

**Comment by Correct-Syntax** [comment]
I can understand that. Actually, the preference here would be snake case for variables as seen in the rest of the code. It isn't conventional to use camel case or pascal case for functions in Python like we do here (so I understand it can be confusing), but it's done that way for consistency with wxPython. Nevertheless, great job on this. I am not too worried about the ``build.py`` script looking perfect personally.

**Comment by instance-id** [comment]
If it's all the same to you, once I finish with work today I want to go back and fix it, it's going to keep bothering me that I missed those. Do I just submit another request or is there a way with git to make additional changes to this one?

**Comment by Correct-Syntax** [comment]
@instance-id sure go ahead and open a new PR for the changes. Thanks again. 😃

**Pull request merged**
