### PR TITLE
UI: Rename “Nodegraph” to “Node Graph”

### PR DESCRIPTION
**Pull request by JohJakob**
- Rename “Nodegraph” to “Node Graph” in user interface

### CODE REVIEW

**Review by iwoithe — APPROVED** [review]
I am fine with this PR however I need @Correct-Syntax to check this before he/I merges it. If merged, I would suggest you creating a similar pull request for the [gsnodegraph](https://github.com/GimelStudio/gsnodegraph) repository. :slightly_smiling_face:

**Comment by Correct-Syntax** [comment]
I was actually debating about renaming the area, "Node Editor". "Node Graph" and "Node Editor" are fairly similar in meaning, though. I've noticed that Natron uses the former, while Blender uses the latter.

Not to be picky, but what's your thoughts @iwoithe and @JohJakob ?

**Comment by iwoithe** [comment]
> what's your thoughts @iwoithe

Now that you mention the term "Node Editor", I think I like that better than "Node Graph". To me, the "Node Editor" is what the user interacts with to edit the project. I feel that "Node Graph" is really just another way of saying "Node Tree". Hope that makes sense. :slightly_smiling_face:

**Comment by Correct-Syntax** [comment]
Agreed. Though, I don't think it needs to be changed urgently. It can wait. 😄

**Pull request merged**
